x-airflow-common: &airflow-common
  image: apache/airflow:3.0.0-python3.12
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@db:5432/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=true
    - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://airflow-api-server:8080/execution/
    - AIRFLOW__API_AUTH__JWT_SECRET=thisismysupersecretkeyforairflowexecution
    - AIRFLOW__WEBSERVER__SECRET_KEY=thisisanothersecretkeyforairflowwebserver
    # Gives Airflow access to pandas for our DAGs!
    - _PIP_ADDITIONAL_REQUIREMENTS=pandas numpy
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: postgres:15
    container_name: taxi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxifare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d # Initializes both taxifare & airflow DBs!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taxifare" ]
      interval: 5s
      timeout: 5s
      retries: 5

  model_service:
    build:
      context: ./model_service
      dockerfile: Dockerfile
    container_name: taxi_api
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/taxifare
      MODEL_PATH: /app/saved_model/taxi_model.pkl
      FEATURES_PATH: /app/saved_model/features.pkl
    ports:
      - "8000:8000"
    volumes:
      - ./model/saved_model:/app/saved_model
    depends_on:
      db:
        condition: service_healthy
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: taxi_frontend
    ports:
      - "8501:8501"
    depends_on:
      - model_service
    restart: always

  # --- AIRFLOW 3 CONTAINERS ---
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@db:5432/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas numpy
    depends_on:
      db:
        condition: service_healthy

  airflow-api-server:
    <<: *airflow-common
    container_name: airflow_api_server
    command: api-server
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow_dag_processor
    command: dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_data:
